version: '3'

services:
  agri-buddy:
    build: .
    container_name: agri-buddy-backend
    restart: always
    ports:
      - "3000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./database:/app/database
    environment:
      - OPENAI_API_KEY=your_api_key
      - DISEASE_DETECTION_API_ENDPOINT=https://your_api_key/
      - WEATHER_API_KEY=your_api_key
    networks:
      - agri-buddy-network

networks:
  agri-buddy-network:
    driver: bridge