name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      
    - name: Set up environment variables in docker-compose.yml
      run: |
        sed -i "s|your_openai_api_key|${{ secrets.OPENAI_API_KEY }}|g" docker-compose.yml
        sed -i "s|your_disease_detection_api_endpoint|${{ secrets.DISEASE_DETECTION_API_ENDPOINT }}|g" docker-compose.yml
      
    - name: Create Elastic Beanstalk Docker configuration
      run: |
        # Create .ebextensions directory
        mkdir -p .ebextensions
        
        # Create Docker configuration
        cat > .ebextensions/01_docker.config << EOL
        option_settings:
          aws:elasticbeanstalk:application:environment:
            COMPOSE_PROJECT_NAME: agri-buddy
        
        container_commands:
          01_install_docker_compose:
            command: |
              curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              chmod +x /usr/local/bin/docker-compose
          02_docker_compose_up:
            command: |
              cd /var/app/current
              /usr/local/bin/docker-compose up -d
        EOL
        
    - name: Generate deployment package
      run: |
        # Make sure we include all necessary files for Docker deployment
        zip -r deploy.zip . -x ".git*" ".github*"
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: agribuddy-backend
        environment_name: Agribuddy-backend-env
        region: eu-north-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
        wait_for_environment_recovery: 600  
