name: Deploy to AWS Elastic Beanstalk with Docker
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: agribuddy-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Create Dockerrun.aws.json
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: agribuddy-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cat > Dockerrun.aws.json <<EOL
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": "5000",
                "HostPort": "80"
              }
            ],
            "Volumes": [
              {
                "HostDirectory": "/var/app/current/uploads",
                "ContainerDirectory": "/app/uploads"
              },
              {
                "HostDirectory": "/var/app/current/database",
                "ContainerDirectory": "/app/database"
              }
            ],
            "Logging": "/var/log/nginx"
          }
          EOL
      - name: Create .ebextensions for environment variables
        run: |
          mkdir -p .ebextensions
          cat > .ebextensions/env-variables.config <<EOL
          option_settings:
            aws:elasticbeanstalk:application:environment:
              OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
              DISEASE_DETECTION_API_ENDPOINT: ${{ secrets.DISEASE_DETECTION_API_ENDPOINT }}
              
          EOL
      - name: Generate deployment package
        run: zip -r deploy.zip Dockerrun.aws.json .ebextensions
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: agribuddy-backend
          environment_name: Agribuddy-backend-env-1
          region: eu-north-1
          version_label: docker-${{ github.sha }}
          deployment_package: deploy.zip
