name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      
    - name: Create Procfile
      run: echo "web: gunicorn --bind=0.0.0.0:5000 app:app" > Procfile
      
    - name: Update requirements.txt
      run: |
        if ! grep -q "gunicorn" requirements.txt; then
          echo "gunicorn" >> requirements.txt
        fi
      
    - name: Create necessary EB config files
      run: |
        mkdir -p .platform/hooks/predeploy
        echo "#!/bin/bash" > .platform/hooks/predeploy/01_setup.sh
        echo "pip install -r requirements.txt" >> .platform/hooks/predeploy/01_setup.sh
        chmod +x .platform/hooks/predeploy/01_setup.sh
        
    - name: Generate deployment package
      run: zip -r deploy.zip . -x "*.git*"
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: agribuddy-backend
        environment_name: Agribuddy-backend-env
        region: eu-north-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
